services:
  nginx:
    image: nginx:latest
    container_name: aetheris-nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./apps:/usr/share/nginx/html/apps
      - ./apps/landing:/usr/share/nginx/html
    restart: unless-stopped










