services:
  nginx:
    image: nginx:stable
    container_name: nginx-Aetheris
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./apps/landing:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
