services:
  nginx:
    image: nginx:latest
    container_name: aetheris-nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./apps:/usr/share/nginx/html/apps
    restart: unless-stopped










