services:
  nginx:
    image: nginx:latest
    container_name: aetheris-nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./apps:/usr/share/nginx/html/apps
    networks:
      - aetheris-web
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:8.2.30-fpm
    container_name: aetheris-fpm
    volumes:
      - ./apps:/usr/share/nginx/html/apps
    networks:
      - aetheris-web
    restart: unless-stopped

networks:
  aetheris-web:

